apiVersion: v1
kind: Service
metadata:
  name: poke-api-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
  labels:
    app: poke-api
    release: prometheus
    self-monitor: "true"
spec:
  type: LoadBalancer
  selector:
    app: poke-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: "poke-port"
