# Generated by Django 5.0 on 2023-12-24 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sprite', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pokemon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
