# Generated by Django 5.0 on 2023-12-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0002_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
